# Generated by Django 4.0 on 2022-01-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="menu",
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="my_restaurant.restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="photo",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="my_restaurant.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="my_restaurant.restaurant",
            ),
        ),
    ]
